<?php
include("include/header.php");
?>
        <!-- Services-->
        <section class="page-section" id="services">
            <div class="container">
                <!-- #######  YAY, I AM THE SOURCE EDITOR! #########-->
<h1 class="CDt4Ke zfr3Q" dir="ltr">Impressum</h1>
<p class="CDt4Ke zfr3Q" dir="ltr">Angaben gem. &sect; 5 TMG:</p>
<p class="CDt4Ke zfr3Q" dir="ltr">FAIR Schulungszentrum.de</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Tieringerstra&szlig;e 31/1</p>
<p class="CDt4Ke zfr3Q" dir="ltr">72336 Balingen</p>
<p class="CDt4Ke zfr3Q" dir="ltr">&nbsp;</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Kontaktaufnahme:</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Telefon: 0173-1840661</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Fax:</p>
<p class="CDt4Ke zfr3Q" dir="ltr">E-Mail: info@fair-schulungszentrum.de</p>
<p class="CDt4Ke zfr3Q" dir="ltr">&nbsp;</p>
<p class="CDt4Ke zfr3Q" dir="ltr"><strong>Umsatzsteuer-ID</strong></p>
<p class="CDt4Ke zfr3Q" dir="ltr">&nbsp;</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Umsatzsteuer-Identifikationsnummer gem. &sect; 27 a Umsatzsteuergesetz:</p>
<p class="CDt4Ke zfr3Q" dir="ltr">DE 344238935</p>
<p class="CDt4Ke zfr3Q" dir="ltr">&nbsp;</p>
<p class="CDt4Ke zfr3Q" dir="ltr"><strong>Haftungsausschluss &ndash; Disclaimer:</strong></p>
<p class="CDt4Ke zfr3Q" dir="ltr">Haftung f&uuml;r Inhalte</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Alle Inhalte unseres Internetauftritts wurden mit gr&ouml;&szlig;ter Sorgfalt und nach bestem Gewissen erstellt. F&uuml;r die Richtigkeit, Vollst&auml;ndigkeit und Aktualit&auml;t der Inhalte k&ouml;nnen wir jedoch keine Gew&auml;hr &uuml;bernehmen. Als Diensteanbieter sind wir gem&auml;&szlig; &sect; 7 Abs.1 TMG f&uuml;r eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach &sect;&sect; 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, &uuml;bermittelte oder gespeicherte fremde Informationen zu &uuml;berwachen oder nach Umst&auml;nden zu forschen, die auf eine rechtswidrige T&auml;tigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unber&uuml;hrt.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Eine diesbez&uuml;gliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntniserlangung einer konkreten Rechtsverletzung m&ouml;glich. Bei Bekanntwerden von den o.g. Rechtsverletzungen werden wir diese Inhalte unverz&uuml;glich entfernen.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Haftungsbeschr&auml;nkung f&uuml;r externe Links</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Unsere Webseite enth&auml;lt Links auf externe Webseiten Dritter. Auf die Inhalte dieser direkt oder indirekt verlinkten Webseiten haben wir keinen Einfluss. Daher k&ouml;nnen wir f&uuml;r die &bdquo;externen Links&ldquo; auch keine Gew&auml;hr auf Richtigkeit der Inhalte &uuml;bernehmen. F&uuml;r die Inhalte der externen Links sind die jeweilige Anbieter oder Betreiber (Urheber) der Seiten verantwortlich.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Die externen Links wurden zum Zeitpunkt der Linksetzung auf eventuelle Rechtsverst&ouml;&szlig;e &uuml;berpr&uuml;ft und waren im Zeitpunkt der Linksetzung frei von rechtswidrigen Inhalten. Eine st&auml;ndige inhaltliche &Uuml;berpr&uuml;fung der externen Links ist ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht m&ouml;glich. Bei direkten oder indirekten Verlinkungen auf die Webseiten Dritter, die au&szlig;erhalb unseres Verantwortungsbereichs liegen, w&uuml;rde eine Haftungsverpflichtung ausschlie&szlig;lich in dem Fall nur bestehen, wenn wir von den Inhalten Kenntnis erlangen und es uns technisch m&ouml;glich und zumutbar w&auml;re, die Nutzung im Falle rechtswidriger Inhalte zu verhindern.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Diese Haftungsausschlusserkl&auml;rung gilt auch innerhalb des eigenen Internetauftrittes &bdquo;<em>Name Ihrer Domain</em>&ldquo; gesetzten Links und Verweise von Fragestellern, Blogeintr&auml;gern, G&auml;sten des Diskussionsforums. F&uuml;r illegale, fehlerhafte oder unvollst&auml;ndige Inhalte und insbesondere f&uuml;r Sch&auml;den, die aus der Nutzung oder Nichtnutzung solcherart dargestellten Informationen entstehen, haftet allein der Diensteanbieter der Seite, auf welche verwiesen wurde, nicht derjenige, der &uuml;ber Links auf die jeweilige Ver&ouml;ffentlichung lediglich verweist.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Werden uns Rechtsverletzungen bekannt, werden die externen Links durch uns unverz&uuml;glich entfernt.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Urheberrecht</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Die auf unserer Webseite ver&ouml;ffentlichen Inhalte und Werke unterliegen dem deutschen Urheberrecht (<a class="XqQF9c rXJpyf" href="http://www.google.com/url?q=http%3A%2F%2Fwww.gesetze-im-internet.de%2Fbundesrecht%2Furhg%2Fgesamt.pdf&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw28JumwSwMOD54F8EilMWQe" target="_blank" rel="noopener">http://www.gesetze-im-internet.de/bundesrecht/urhg/gesamt.pdf</a>) . Die Vervielf&auml;ltigung, Bearbeitung, Verbreitung und jede Art der Verwertung des geistigen Eigentums in ideeller und materieller Sicht des Urhebers au&szlig;erhalb der Grenzen des Urheberrechtes bed&uuml;rfen der vorherigen schriftlichen Zustimmung des jeweiligen Urhebers i.S.d. Urhebergesetzes (<a class="XqQF9c rXJpyf" href="http://www.google.com/url?q=http%3A%2F%2Fwww.gesetze-im-internet.de%2Fbundesrecht%2Furhg%2Fgesamt.pdf&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw28JumwSwMOD54F8EilMWQe" target="_blank" rel="noopener">http://www.gesetze-im-internet.de/bundesrecht/urhg/gesamt.pdf</a> ). Downloads und Kopien dieser Seite sind nur f&uuml;r den privaten und nicht kommerziellen Gebrauch erlaubt. Sind die Inhalte auf unserer Webseite nicht von uns erstellt wurden, sind die Urheberrechte Dritter zu beachten. Die Inhalte Dritter werden als solche kenntlich gemacht. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte unverz&uuml;glich entfernen.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Quellen:</p>
<ul>
  <li>Hände (<a href="https://www.zukunftsinstitut.de/index.php?eID=tx_cms_showpic&file=691&md5=eee1061edbcc903de7c04b1163c2d1309b0ee7e8&parameters%5B0%5D=YToyOntzOjc6ImJvZHlUYWciO3M6NDE6Ijxib2R5IHN0eWxlPSJtYXJnaW46MDsg&parameters%5B1%5D=YmFja2dyb3VuZDojZmZmOyI%2BIjtzOjQ6IndyYXAiO3M6MTY4OiI8ZGl2IHN0eWxl&parameters%5B2%5D=PSJoZWlnaHQ6IDEwMCU7IG92ZXJmbG93OiBhdXRvOyB0ZXh0LWFsaWduOiBjZW50&parameters%5B3%5D=ZXI7Ij4KPGEgaHJlZj0iamF2YXNjcmlwdDpjbG9zZSgpOyIgdGl0bGU9IktsaWNr&parameters%5B4%5D=ZW4genVtIFNjaGxpZcOfZW4iIGFsdD0iS2xpY2tlbiB6dW0gU2NobGllw59lbiI%2B&parameters%5B5%5D=IHwgPC9hPgo8L2Rpdj4iO30%3D">hier</a>)</li>
  <li>Bild lernen (<a href="https://www.studienstrategie.de/wp-content/uploads/2021/12/multiple-choice-tests-und-fragen-bestehen-lernpsychologe-drmartinkrengel.png">hier</a>)</li>
  <li>Lehrer (<a href="https://infode.examtime.com/files/2013/10/lehrerkompetenzen-examtime.jpg">hier</a>)</li>
  <li>Gehirn (<a href="https://www.habitgym.de/wp-content/uploads/2017/07/Lernmethoden-So-funktioniert-lernen.png">hier</a>)</li>
</ul>
<p class="CDt4Ke zfr3Q" dir="ltr">&nbsp;</p>
<p class="CDt4Ke zfr3Q" dir="ltr">&nbsp;</p>
<p class="CDt4Ke zfr3Q" dir="ltr">&nbsp;</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Dieses <a class="XqQF9c rXJpyf" href="https://www.google.com/url?q=https%3A%2F%2Fjurarat.de%2Fmuster-impressum&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw1HiuUoh4deEfi_89lmSwWF" target="_blank" rel="noopener">Impressum</a> wurde freundlicherweise von <a class="XqQF9c rXJpyf" href="https://www.google.com/url?q=https%3A%2F%2Fjurarat.de%2F&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw0Fg2fTLRick2h1-JBGDPu8" target="_blank" rel="noopener">jurarat.de</a> zur Verf&uuml;gung gestellt.</p>
<h1 style="color: #5e9ca0;">&nbsp;</h1>
				<!-- #######  YAY, I AM THE SOURCE EDITOR! #########-->
<h1 class="CjVfdc"><span class=" jW0mOd"><strong>Datenschutz</strong></span></h1>
<p class="CDt4Ke zfr3Q" dir="ltr">Die Nutzung unserer Website (Name Ihrer Domain) ist in der Regel ohne Angabe personenbezogener Daten m&ouml;glich. Soweit auf unserer Seite personenbezogene Daten (beispielsweise Name, Anschrift, E-Mail-Adressen, im Rahmen einer Warenbestellung, Er&ouml;ffnung und bei Registrierung f&uuml;r unseren Newsletter) doch erhoben werden sollte, erfolgt dies, soweit es uns m&ouml;glich ist, nur auf freiwilliger Basis (vgl. &sect; 13 TMG). Die sensiblen Daten werden ohne Ihre ausdr&uuml;ckliche Zustimmung nicht an Dritte weitergegeben. Wir weisen darauf Aufmerksam machen, dass die Daten&uuml;bertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitsl&uuml;cken aufweisen kann. Ein l&uuml;ckenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht m&ouml;glich. Die &Uuml;bersendung von nicht ausdr&uuml;cklich angeforderter Werbung und Informationsmaterialien durch die Benutzung der Kontaktdaten, die im Rahmen der Erf&uuml;llung der Impressumspflicht gem. &sect; 5 TMG preisgegeben werden, wird hiermit ausdr&uuml;cklich widersprochen. Wir behalten uns ausdr&uuml;cklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-Mails (insbesondere Newsletter), vor.</p>
<p class="CDt4Ke zfr3Q" dir="ltr"><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Facebook-Plugins (Like-Button)</strong></p>
<p class="CDt4Ke zfr3Q" dir="ltr">Auf unseren Seiten sind Plugins des sozialen Netzwerks Facebook, 1601 South California Avenue, Palo Alto, CA 94304, USA integriert. Diese erkennen Sie an dem Facebook-Logo oder dem &ldquo;Like-Button&rdquo; (&ldquo;Gef&auml;llt mir&rdquo;) auf unserer Seite. Eine &Uuml;bersicht &uuml;ber m&ouml;gliche Facebook-Plugins finden Sie unter folgendem Link: <span class=" aw5Odc"><a class="XqQF9c" href="http://www.google.com/url?q=http%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw0fF4784bh0JGqJpHMy9x_N" target="_blank" rel="noopener">http://developers.facebook.com/docs/plugins/</a></span></p>
<p class="CDt4Ke zfr3Q" dir="ltr">. Aufgrund dieser Facebook-Plugins (Like-Button) wird eine direkte Verbindung zwischen Ihrem Browser und dem Facebook-Server hergestellt, falls Sie unsere Seiten besuchen. Durch Ihren Besuch erh&auml;lt Facebook Informationen, dass Sie mit Ihrer IP-Adresse unsere Seiten besucht haben. Klicken Sie nun auf den Facebook &bdquo;Like-Button&ldquo; (Gef&auml;llt mir) auf unserer Seiten w&auml;hrend Sie zeitgleich in Ihrem Facebook-Account angemeldet sind, werden die Inhalte unserer Seiten auf Ihrem Facebook-Profil verlinkt. Folglich kann Facebook Ihren Besuch auf unserer Seite zu Ihrem Benutzerkonto zuordnen. Wir, als Diensteanbieter, weisen darauf hin, dass wir als Webseiten-Anbieter keine Kenntnis vom Inhalt der &uuml;bermittelten Daten sowie deren Nutzung durch Facebook erhalten. Daher verweisen wir zur Erlangung weiterer Informationen bez&uuml;glich der Datenschutzerkl&auml;rung von Facebook auf folgenden Link: <span class=" aw5Odc"><a class="XqQF9c" href="http://www.google.com/url?q=http%3A%2F%2Fde-de.facebook.com%2Fpolicy.php&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw3b365aNdY-XSP0ziUIeWwY" target="_blank" rel="noopener">http://de-de.facebook.com/policy.php</a></span></p>
<p class="CDt4Ke zfr3Q" dir="ltr">Ist es von Ihnen nicht gew&uuml;nscht, dass Facebook Ihren Aufenthalt auf unserer Website auf Ihren Facebook-Nutzerkonto zuordnet, bitten wir Sie, bei Ihrem Aufenthalt auf unserer Website, sich aus Ihrem Facebook-Benutzerkonto abzumelden.</p>
<p class="CDt4Ke zfr3Q" dir="ltr"><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Google Analytics</strong></p>
<p class="CDt4Ke zfr3Q" dir="ltr">Unsere Website benutzt Google Analytics, einen Webanalysedienst der Google Inc. (&ldquo;Google&rdquo;). F&uuml;r diesen Webanalysedienst benutzt Google Analytics sogenannte &bdquo;Cookies&ldquo;, d.h. das Textdateien auf ihrem Computer gespeichert werden, die dann wiederum eine Analyse der Benutzung der Website durch Sie erm&ouml;glichen. Die Informationen, die durch den Cookie &uuml;ber die Benutzung unserer Website erzeugt werden, werden an einen Server von Google in den USA &uuml;bertragen und anschlie&szlig;end dort gespeichert. Kommt es zu einer Aktivierung der IP-Anonymisierung auf unserer Website, so wird Ihre IP-Adresse von Google nur innerhalb von den Mitgliedstaaten der EU oder in anderen Vertragsstaaten des Abkommens &uuml;ber den Europ&auml;ischen Wirtschaftsraum vorher gek&uuml;rzt. Dabei kann in wenigen Ausnahmef&auml;llen die volle IP-Adresse an einen Server von Google in den USA &uuml;bertragen werden und dann dort gek&uuml;rzt werden. Google kann dann aufgrund dieser Informationen, die gespeichert werden, Ihre Nutzung der Website auswerten, um sodann eine Zusammenstellung eines Reports &uuml;ber die Werbseitenaktivit&auml;ten bereitzustellen. Aufgrund dieses Reportes kann Google dann auch weitere mit der Websitennutzung und der Internetnutzung verbundene Dienstleistungen gegen&uuml;ber dem Websiten-Anbieter erbringen. Die &uuml;ber Google Analytics von Ihrem Browser &uuml;bermittelte IP-Adresse wird nicht mit anderen Daten von Google zusammen gef&uuml;hrt. Liegt diese Auswertung anhand Ihres Aufenthaltes auf unserer Seite nicht in Ihrem Interesse, so k&ouml;nnen sie die Speicherung oder Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern. Gleichzeitig m&ouml;chten wir Sie in Kenntnis dar&uuml;ber setzen, dass Sie in diesem Fall s&auml;mtliche Funktionen unserer Website nicht vollumf&auml;nglich nutzen k&ouml;nnen.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Durch die Nutzung dieser Website erkl&auml;ren Sie sich mit der Bearbeitung der &uuml;ber Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden. Ferner k&ouml;nnen sie die Erfassung der durch den Cookie erzeugten und auf Ihre Nutzung der Website bezogenen Daten an Google sowie die Verarbeitung dieser Daten durch Google verhindern, indem sie das unter dem folgenden Link verf&uuml;gbare Browser-Plugin herunterladen und installieren: <span class=" aw5Odc"><a class="XqQF9c" href="http://tools.google.com/dlpage/gaoptout?hl=de" target="_blank" rel="noopener">http://tools.google.com/dlpage/gaoptout?hl=de</a></span></p>
<p class="CDt4Ke zfr3Q" dir="ltr"><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Google AdSense</strong></p>
<p class="CDt4Ke zfr3Q" dir="ltr">Unsere Website benutzt Google AdSense, einen Dienst zum Einbinden von Werbeanzeigen der Google Inc. (&ldquo;Google&rdquo;). F&uuml;r diesen Dienst zum Einbinden von Werbeanzeigen verwendet Google AdSense so genannte &ldquo;Cookies&rdquo;, Textdateien, die auf Ihrem Computer gespeichert werden und die eine Analyse der Benutzung der Website erm&ouml;glicht. Dar&uuml;ber hinaus verwendet Google AdSense auch Web Beacons (unsichtbare Grafiken). Aufgrund von den Web Beacons k&ouml;nnen Informationen wie der Besucherverkehr auf Websiten ausgewertet werden. Anhand der Cookies und den Web Beacons werden Informationen &uuml;ber die Benutzung unserer Website, inbegriffen Ihrer IP-Adresse, erzeugt. Die Auslieferung von Werbeformaten wird dann an einen Server von Google in den USA &uuml;bertragen und dort, wie bei Google Analytics, gespeichert. Die gespeicherten Informationen k&ouml;nnen dann von Google weiter an deren Vertragspartner gegeben werden. Dennoch werden die von Google erhobenen Informationen &uuml;ber Ihre IP-Adresse nicht mit anderen von Ihnen gespeicherten Daten zusammen gef&uuml;hrt Liegt diese Erfassung der Informationen anhand Ihres Aufenthaltes auf unserer Seite nicht in Ihrem Interesse, so k&ouml;nnen sie die Speicherung oder Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern. Gleichzeitig m&ouml;chten wir Sie in Kenntnis dar&uuml;ber setzen, dass Sie in diesem Fall s&auml;mtliche Funktionen dieser Website nicht vollumf&auml;nglich nutzen k&ouml;nnen. Durch die Nutzung dieser Website erkl&auml;ren Sie sich mit der Bearbeitung der &uuml;ber Sie erhobenen Daten durch Google in der zuvor beschriebenen Art und Weise und zu dem zuvor benannten Zweck einverstanden.</p>
<p class="CDt4Ke zfr3Q" dir="ltr"><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Google +1</strong></p>
<p class="CDt4Ke zfr3Q" dir="ltr">Erfassung und Weitergabe von Informationen: Mit Google +1 k&ouml;nnen Informationen weltweit ver&ouml;ffentlich werden. Anhand der Google +1 &ndash; Schaltfl&auml;che k&ouml;nnen Sie und andere Nutzer/Nutzerinnen personalisierte Inhalte von Google und unseren Partnern erhalten.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Dabei werden von Google Informationen gespeichert:</p>
<p class="CDt4Ke zfr3Q" dir="ltr">1. wenn Sie f&uuml;r einen Inhalt +1 gegeben haben und</p>
<p class="CDt4Ke zfr3Q" dir="ltr">2. wenn Sie sich Informationen &uuml;ber die Seite beim Klicken auf +1 angesehen haben</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Mit Ihrem Profilnamen und Ihrem Foto k&ouml;nnen auch Ihre Google +1 Hinweise in Google-Diensten, in Ihren Suchergebnissen, auf anderen Websiten im Internet angezeigt werden. Durch Ihre +1 Aktivit&auml;ten, kann Google Informationen zusammen stellen, um die Google Dienste f&uuml;r Sie zu verbessern. Damit Sie die Google +1 Schaltfl&auml;che benutzen k&ouml;nnen, m&uuml;ssen Sie ein weltweit sichtbares, &ouml;ffentliches Google-Profil haben. Ihr Google-Profil besitzt dabei einen Namen, womit Sie in allen Google-Diensten erscheinen, die wiederum Ihre gesamten Aktivit&auml;ten in Ihrem Profil darstellen. Dar&uuml;ber hinaus k&ouml;nnen Nutzer/Nutzerinnen, die ebenfalls bei Google angemeldet (ein Profil besitzen) sind und Ihre E-Mail Adresse kennen oder &uuml;ber andere identifizierende Informationen von Ihnen besitzen, Ihr Profil sehen. Verwendung der erfassten Informationen: Abgesehen von den oben angef&uuml;hrten Verwendungszwecken sind die von Ihnen bereit gestellten Informationen gem. den geltenden Google-Datenschutzbestimmungen zu verwenden. Es kann die M&ouml;glichkeit bestehen, dass Google zusammen gefasste Statistiken &uuml;ber die Google +1 Aktivit&auml;ten der Nutzer/Nutzerinnen ver&ouml;ffentlichen. Auch kann die M&ouml;glichkeit bestehen, dass Google die Informationen an Nutzer/Nutzerinnen und Partner/Partnerinnen weitergeben kann (z.B. Publisher, Inserenten oder verbunden Websiten).</p>
<p class="CDt4Ke zfr3Q" dir="ltr"><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Twitter</strong></p>
<p class="CDt4Ke zfr3Q" dir="ltr">Unsere Website benutzt auch Funktionen des Dienstes Twitter. Die Funktionen werden durch die Twitter Inc., 795 Folsom St., Suite 600, San Francisco, CA 94107, USA angeboten. Aufgrund des Benutzen von Twitter und der Funktion &bdquo;Re-Tweet&ldquo; werden die von Ihnen besuchten Website mit Ihrem Twitter-Account verlinkt und anderen Nutzern/Nutzerinnen bekannt gegeben. Bei dieser Datenweiterleitung werden auch Daten an Twitter &uuml;bertragen. Wir, als Diensteanbieter, weisen darauf hin, dass wir als Websiten-Anbieter keine Kenntnis vom Inhalt der &uuml;bermittelten Daten sowie deren Nutzung durch Twitter erhalten. Daher verweisen wir zur Erlangung weiterer Informationen bez&uuml;glich der Datenschutzerkl&auml;rung von Twitter auf folgenden Link: <span class=" aw5Odc"><a class="XqQF9c" href="http://www.google.com/url?q=http%3A%2F%2Ftwitter.com%2Fprivacy&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw323RRWEXF5I58N7aQ6UNU8" target="_blank" rel="noopener">http://twitter.com/privacy</a></span></p>
<p class="CDt4Ke zfr3Q" dir="ltr">Falls Sie Ihre Datenschutzeinstellungen bei Twitter &auml;ndern wollen, k&ouml;nnen Sie dies unter diesem Link vornehmen: <span class=" aw5Odc"><a class="XqQF9c" href="http://www.google.com/url?q=http%3A%2F%2Ftwitter.com%2Faccount%2Fsettings&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw2WVBMlxifkiaTUoYNH8k55" target="_blank" rel="noopener">http://twitter.com/account/settings</a></span></p>
<p class="CDt4Ke zfr3Q" dir="ltr"><strong>Datenschutzerkl&auml;rung f&uuml;r die Nutzung von Piwik:</strong></p>
<p class="CDt4Ke zfr3Q" dir="ltr">Unsere Website benutzt Piwik, ein Webanalysedienst zur statistischen Auswertung von Besucherzugriffen &auml;hnlich wie Google Analytics.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">F&uuml;r diesen Webanalysedienst benutzt Piwik sogenannte &bdquo;Cookies&ldquo;, d.h. das Textdateien auf Ihrem Computer gespeichert werden, die dann wiederum eine Analyse der Benutzung der Website durch Sie erm&ouml;glichen.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Die Informationen, die durch den Cookie &uuml;ber die Benutzung unserer Website erzeugt werden, werden an unseren Server &uuml;bertragen und anschlie&szlig;end dort zu Nutzungsanalysezwecken gespeichert. Dies dient f&uuml;r unsere Websitenoptimierung.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Bei der Erhebung Ihrer Informationen durch den Cookie wird die IP-Adresse umgehend anonymisiert, d.h. die Nutzer/die Nutzerinnen bleiben anonym. Ferner werden die erhobenen Informationen nicht an Dritte weitergegeben.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Liegt diese Auswertung anhand Ihres Aufenthaltes (durch Ihre IP-Adresse) auf unserer Seite nicht in Ihrem Interesse, so k&ouml;nnen Sie die Speicherung oder Installation der Cookies durch eine entsprechende Einstellung Ihrer Browser-Software verhindern. Gleichzeitig m&ouml;chten wir Sie in Kenntnis dar&uuml;ber setzen, dass Sie in diesem Fall s&auml;mtliche Funktionen unserer Website nicht vollumf&auml;nglich nutzen k&ouml;nnen.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Es liegt Ihnen frei dar&uuml;ber zu entscheiden, ob in Ihrem Internet-Browser Cookies, die im Rahmen des Einsatzes von Piwik, der dem Websiten-Besitzer die Analyse verschiedener Statistiken erm&ouml;glicht, abgelegt werden oder nicht. Falls Sie die Zustimmung zur Erhebung von Informationen durch den Cookie nicht erteilen wollen, k&ouml;nnen Sie folgenden <span class=" aw5Odc"><a class="XqQF9c" href="https://www.google.com/url?q=https%3A%2F%2Fjurarat.de%2F%3Fcmd%3Dpwkignore&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw0woV7z0TZgfMzg2hcq5Hys" target="_blank" rel="noopener">Link </a></span>anklicken. Dadurch wird Ihr Besuch nicht mehr erfasst.</p>
<p class="CDt4Ke zfr3Q" dir="ltr">Diese <span class=" aw5Odc"><a class="XqQF9c" href="https://www.google.com/url?q=https%3A%2F%2Fjurarat.de%2Fmuster-datenschutzerklaerung&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw1POMWp2Hs8vL-ETnCaV7e8" target="_blank" rel="noopener">Datenschutzerkl&auml;rung</a></span> wurde freundlicherweise von <span class=" aw5Odc"><a class="XqQF9c" href="https://www.google.com/url?q=https%3A%2F%2Fjurarat.de%2F&amp;sa=D&amp;sntz=1&amp;usg=AOvVaw0Fg2fTLRick2h1-JBGDPu8" target="_blank" rel="noopener">jurarat.de</a></span> zur Verf&uuml;gung gestellt.</p>
<h1 class="CDt4Ke zfr3Q" dir="ltr">&nbsp;</h1>
				
            </div>
        </section>      
       
      


        <?php
include("include/footer.php");
?>